from math import *
print("this is max number=")
print(max(200,300))
print("this is min number=")
print(min(5,10))
print("this is abs number=")
print(abs(-4))
print("this is sqrt number=")
print(sqrt(25))
print("this is round number=")
print(round(3.2))
